id: A589394C1
title: 'Offering Clouds of Samantabhadra: Confession and Fulfilment'
type: translation
pechas:
- I7D0A769F
- I73DDF3C3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:53.821160
  last_modified_at: 2023-01-04 12:50:53.821182
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I7D0A769F/B8B8: 19C3
  I73DDF3C3/5ABB: 19C3
